import type { DisruptionEvent, LedgerEntry, OperationalEvent, Shipment, User } from "./types";

/** Seeded operational data. Demo dataset — not a live external feed. */

export const DEMO_USERS: User[] = [
  {
    id: "u-planner",
    name: "M. Okonkwo",
    email: "planner@sentinelflash.demo",
    role: "planner",
    org: "Global Ocean Control",
  },
  {
    id: "u-approver",
    name: "L. Vandermeer",
    email: "approver@sentinelflash.demo",
    role: "approver",
    org: "Network Risk Authority",
  },
  {
    id: "u-editor",
    name: "A. Rivera",
    email: "editor@sentinelflash.demo",
    role: "editor",
    org: "Shipment Data Operations",
  },
];

export const SEED_SHIPMENTS: Shipment[] = [
  {
    id: "SF-1001",
    origin: { name: "Ningbo", code: "CNNGB", lat: 29.87, lon: 121.54 },
    destination: { name: "Rotterdam", code: "NLRTM", lat: 51.95, lon: 4.14 },
    position: { lat: 12.4, lon: 60.2 },
    cargo: "Consumer electronics",
    cargoValueUsd: 180000,
    mode: "ocean",
    vessel: "MV Hanjin Meridian",
    etaIso: "2026-09-28T08:00:00.000Z",
    riskScore: 38,
    status: "monitoring",
    coldChain: false,
    constraints: ["Contractual delivery window: 5 days float"],
    demoScenario: true,
  },
  {
    id: "SF-1002",
    origin: { name: "Antwerp", code: "BEANR", lat: 51.26, lon: 4.4 },
    destination: { name: "Mombasa", code: "KEMBA", lat: -4.04, lon: 39.66 },
    position: { lat: 31.2, lon: 18.9 },
    cargo: "Vaccines (2–8 °C)",
    cargoValueUsd: 620000,
    mode: "ocean",
    vessel: "MV Scheldt Carrier",
    etaIso: "2026-09-24T06:00:00.000Z",
    riskScore: 61,
    status: "monitoring",
    coldChain: true,
    constraints: [
      "COLD CHAIN: continuous 2–8 °C reefer custody",
      "Max 4h temperature excursion tolerance",
      "GDP-certified handling at every transhipment",
    ],
    demoScenario: true,
  },
  {
    id: "SF-1003",
    origin: { name: "Shanghai", code: "CNSHA", lat: 31.23, lon: 121.47 },
    destination: { name: "Los Angeles", code: "USLAX", lat: 33.74, lon: -118.27 },
    position: { lat: 34.8, lon: 168.4 },
    cargo: "Bulk pharma ingredients (API)",
    cargoValueUsd: 1450000,
    mode: "ocean",
    vessel: "MV Pacific Ridge",
    etaIso: "2026-09-26T15:00:00.000Z",
    riskScore: 57,
    status: "monitoring",
    coldChain: false,
    constraints: [
      "Regulated substance: customs pre-clearance required",
      "Single-carrier custody preferred",
    ],
    demoScenario: true,
  },
  {
    id: "SF-2041",
    origin: { name: "Santos", code: "BRSSZ", lat: -23.95, lon: -46.33 },
    destination: { name: "Hamburg", code: "DEHAM", lat: 53.54, lon: 9.98 },
    position: { lat: 5.2, lon: -28.4 },
    cargo: "Green coffee",
    cargoValueUsd: 240000,
    mode: "ocean",
    vessel: "MV Atlantic Vale",
    etaIso: "2026-10-02T09:00:00.000Z",
    riskScore: 14,
    status: "on_track",
    coldChain: false,
    constraints: [],
    demoScenario: false,
  },
  {
    id: "SF-2042",
    origin: { name: "Busan", code: "KRPUS", lat: 35.1, lon: 129.04 },
    destination: { name: "Seattle", code: "USSEA", lat: 47.6, lon: -122.34 },
    position: { lat: 44.1, lon: -172.6 },
    cargo: "Automotive components",
    cargoValueUsd: 410000,
    mode: "ocean",
    vessel: "MV Dongbaek",
    etaIso: "2026-09-22T12:00:00.000Z",
    riskScore: 22,
    status: "on_track",
    coldChain: false,
    constraints: [],
    demoScenario: false,
  },
  {
    id: "SF-2043",
    origin: { name: "Jebel Ali", code: "AEJEA", lat: 25.01, lon: 55.06 },
    destination: { name: "Felixstowe", code: "GBFXT", lat: 51.95, lon: 1.32 },
    position: { lat: 26.7, lon: 33.1 },
    cargo: "Industrial polymers",
    cargoValueUsd: 305000,
    mode: "ocean",
    vessel: "MV Al Maha",
    etaIso: "2026-09-29T18:00:00.000Z",
    riskScore: 31,
    status: "monitoring",
    coldChain: false,
    constraints: ["Suez transit dependency"],
    demoScenario: false,
  },
  {
    id: "SF-2044",
    origin: { name: "Valencia", code: "ESVLC", lat: 39.44, lon: -0.31 },
    destination: { name: "New York", code: "USNYC", lat: 40.67, lon: -74.05 },
    position: { lat: 38.2, lon: -37.9 },
    cargo: "Chilled dairy (0–4 °C)",
    cargoValueUsd: 185000,
    mode: "ocean",
    vessel: "MV Turia Reefer",
    etaIso: "2026-09-21T07:00:00.000Z",
    riskScore: 27,
    status: "on_track",
    coldChain: true,
    constraints: ["COLD CHAIN: continuous 0–4 °C custody"],
    demoScenario: false,
  },
  {
    id: "SF-2045",
    origin: { name: "Chennai", code: "INMAA", lat: 13.09, lon: 80.29 },
    destination: { name: "Durban", code: "ZADUR", lat: -29.87, lon: 31.02 },
    position: { lat: -3.4, lon: 63.8 },
    cargo: "Textiles",
    cargoValueUsd: 96000,
    mode: "ocean",
    vessel: "MV Coromandel",
    etaIso: "2026-10-05T10:00:00.000Z",
    riskScore: 9,
    status: "on_track",
    coldChain: false,
    constraints: [],
    demoScenario: false,
  },
];

export const SEED_DISRUPTIONS: Record<string, DisruptionEvent> = {
  "SF-1001": {
    id: "DE-1001",
    shipmentId: "SF-1001",
    title: "Rotterdam terminal labour action — berth queue extending",
    category: "Port congestion",
    detectedAtIso: "2026-09-13T06:12:00.000Z",
    location: "Port of Rotterdam, Maasvlakte II",
    summary:
      "Two independent sources report a 48-hour terminal work stoppage. Berth allocation for feeder and mainline calls is slipping by 2–3 days.",
    verified: true,
    sources: [
      {
        id: "EV-1001-A",
        connector: "NewsConnector",
        label: "Terminal work stoppage extended to 48 hours",
        publisher: "Seeded wire feed (demo)",
        observedAtIso: "2026-09-13T05:41:00.000Z",
        summary:
          "Union notice confirms a 48-hour stoppage across two deep-sea terminals; carriers advised to expect berth slippage.",
        confidence: 0.86,
        simulated: true,
      },
      {
        id: "EV-1001-B",
        connector: "PortConnector",
        label: "Berth queue depth 11 vessels (baseline 4)",
        publisher: "Seeded port status feed (demo)",
        observedAtIso: "2026-09-13T06:02:00.000Z",
        summary:
          "Queue depth and average wait time both above the 95th percentile for this terminal.",
        confidence: 0.91,
        simulated: true,
      },
      {
        id: "EV-1001-C",
        connector: "AISConnector",
        label: "AIS confirmation — MV Hanjin Meridian holding pattern",
        publisher: "Seeded AIS snapshot (demo)",
        observedAtIso: "2026-09-13T06:10:00.000Z",
        summary:
          "Vessel speed reduced to 9.4 kn on approach leg, consistent with instructed arrival delay.",
        confidence: 0.94,
        simulated: true,
      },
    ],
  },
  "SF-1002": {
    id: "DE-1002",
    shipmentId: "SF-1002",
    title: "Suez southbound convoy suspension — reefer plug shortage downstream",
    category: "Transit closure",
    detectedAtIso: "2026-09-13T05:48:00.000Z",
    location: "Suez Canal southbound / Djibouti transhipment",
    summary:
      "Southbound convoys suspended for an estimated 72 hours. Downstream transhipment options report no certified reefer plug availability.",
    verified: true,
    sources: [
      {
        id: "EV-1002-A",
        connector: "NewsConnector",
        label: "Southbound convoys suspended pending salvage",
        publisher: "Seeded wire feed (demo)",
        observedAtIso: "2026-09-13T05:20:00.000Z",
        summary:
          "Authority halts southbound transits; northbound unaffected. Estimated 72-hour suspension.",
        confidence: 0.88,
        simulated: true,
      },
      {
        id: "EV-1002-B",
        connector: "PortConnector",
        label: "Djibouti reefer plug availability: 0 certified slots",
        publisher: "Seeded port status feed (demo)",
        observedAtIso: "2026-09-13T05:35:00.000Z",
        summary:
          "Transhipment yard reports zero GDP-certified reefer plugs for the next 96 hours; ambient staging only.",
        confidence: 0.93,
        simulated: true,
      },
      {
        id: "EV-1002-C",
        connector: "AISConnector",
        label: "AIS confirmation — MV Scheldt Carrier drifting north of Port Said",
        publisher: "Seeded AIS snapshot (demo)",
        observedAtIso: "2026-09-13T05:45:00.000Z",
        summary: "Vessel in drift pattern at anchorage, no southbound progress in 6 hours.",
        confidence: 0.95,
        simulated: true,
      },
    ],
  },
  "SF-1003": {
    id: "DE-1003",
    shipmentId: "SF-1003",
    title: "Pacific storm system across great-circle track",
    category: "Severe weather",
    detectedAtIso: "2026-09-13T04:55:00.000Z",
    location: "North Pacific, 168°E corridor",
    summary:
      "Storm system with sustained 45 kn winds intersects the planned track. Routing south adds distance; holding adds demurrage exposure.",
    verified: true,
    sources: [
      {
        id: "EV-1003-A",
        connector: "WeatherConnector",
        label: "Gale warning, sustained 45 kn, 6.5 m significant wave height",
        publisher: "Seeded weather feed (demo)",
        observedAtIso: "2026-09-13T04:30:00.000Z",
        summary:
          "System tracking east at 18 kn, expected to intersect the planned track within 30 hours.",
        confidence: 0.9,
        simulated: true,
      },
      {
        id: "EV-1003-B",
        connector: "PortConnector",
        label: "Los Angeles berth window firm — no slack after 26 Sep",
        publisher: "Seeded port status feed (demo)",
        observedAtIso: "2026-09-13T04:48:00.000Z",
        summary:
          "Missing the window pushes the call to a 4-day later slot with demurrage exposure.",
        confidence: 0.84,
        simulated: true,
      },
      {
        id: "EV-1003-C",
        connector: "AISConnector",
        label: "AIS confirmation — MV Pacific Ridge on planned track, 18.2 kn",
        publisher: "Seeded AIS snapshot (demo)",
        observedAtIso: "2026-09-13T04:52:00.000Z",
        summary: "Vessel position and heading confirm exposure to the forecast system.",
        confidence: 0.96,
        simulated: true,
      },
    ],
  },
};

export const SEED_LEDGER: LedgerEntry[] = [
  {
    id: "LG-20260906-0014",
    timestampIso: "2026-09-06T09:14:22.000Z",
    shipmentId: "SF-2041",
    lane: "Santos → Hamburg",
    decision: "Re-speed +1.5 kn",
    status: "AUTO_COMMITTED",
    actorType: "system",
    actorName: "SYSTEM / AUTONOMOUS",
    reference: "ACT-7F31A2",
    rationale: "Berth window recovery within autonomous thresholds; no hard constraint engaged.",
    decisionSource: "gemini",
    seeded: true,
  },
  {
    id: "LG-20260906-0021",
    timestampIso: "2026-09-06T17:02:55.000Z",
    shipmentId: "SF-2045",
    lane: "Chennai → Durban",
    decision: "Do nothing (baseline retained)",
    status: "AUTO_COMMITTED",
    actorType: "system",
    actorName: "SYSTEM / AUTONOMOUS",
    reference: "ACT-19C7D0",
    rationale: "Recovery cost exceeded modelled cost of inaction; baseline retained.",
    decisionSource: "fallback",
    seeded: true,
  },
  {
    id: "LG-20260908-0033",
    timestampIso: "2026-09-08T11:40:09.000Z",
    shipmentId: "SF-2044",
    lane: "Valencia → New York",
    decision: "Reroute via Algeciras",
    status: "APPROVED_COMMITTED",
    actorType: "human",
    actorName: "L. Vandermeer (Approver)",
    reference: "ACT-2B84EE",
    rationale:
      "Cold-chain leg present; human approval required and granted with reefer custody confirmed.",
    decisionSource: "gemini",
    seeded: true,
  },
  {
    id: "LG-20260909-0041",
    timestampIso: "2026-09-09T08:21:47.000Z",
    shipmentId: "SF-2042",
    lane: "Busan → Seattle",
    decision: "Switch discharge port to Tacoma",
    status: "AUTO_COMMITTED",
    actorType: "system",
    actorName: "SYSTEM / AUTONOMOUS",
    reference: "ACT-55A1C9",
    rationale: "Congestion avoidance; inland drayage delta within tolerance.",
    decisionSource: "gemini",
    seeded: true,
  },
  {
    id: "LG-20260910-0052",
    timestampIso: "2026-09-10T14:05:31.000Z",
    shipmentId: "SF-2043",
    lane: "Jebel Ali → Felixstowe",
    decision: "Reroute via Cape of Good Hope — REFUSED alternative recorded",
    status: "AUTO_COMMITTED",
    actorType: "system",
    actorName: "SYSTEM / AUTONOMOUS",
    reference: "ACT-6D0B13",
    rationale:
      "Cheapest option refused (carrier lacked hazardous-goods endorsement). Cheapest viable alternative committed.",
    decisionSource: "gemini",
    seeded: true,
  },
  {
    id: "LG-20260911-0060",
    timestampIso: "2026-09-11T10:12:04.000Z",
    shipmentId: "SF-2044",
    lane: "Valencia → New York",
    decision: "Re-speed +2.0 kn",
    status: "REJECTED_ESCALATED",
    actorType: "human",
    actorName: "L. Vandermeer (Approver)",
    reference: "ESC-91F4A7",
    rationale: "Bunker exposure rejected pending commercial review; escalated to trade lane owner.",
    decisionSource: "gemini",
    seeded: true,
  },
  {
    id: "LG-20260912-0071",
    timestampIso: "2026-09-12T07:58:12.000Z",
    shipmentId: "SF-2041",
    lane: "Santos → Hamburg",
    decision: "Do nothing (baseline retained)",
    status: "AUTO_COMMITTED",
    actorType: "system",
    actorName: "SYSTEM / AUTONOMOUS",
    reference: "ACT-30E9F5",
    rationale: "Signal did not clear verification threshold for action; monitoring continued.",
    decisionSource: "fallback",
    seeded: true,
  },
  {
    id: "LG-20260912-0078",
    timestampIso: "2026-09-12T19:33:40.000Z",
    shipmentId: "SF-2045",
    lane: "Chennai → Durban",
    decision: "Override — switch mode to rail-sea combination",
    status: "OVERRIDDEN_COMMITTED",
    actorType: "human",
    actorName: "L. Vandermeer (Approver)",
    reference: "ACT-8C22B6",
    rationale: "Approver overrode the recommendation in favour of a lower-risk multimodal routing.",
    decisionSource: "gemini",
    seeded: true,
  },
];

export const SEED_ACTIVITY: OperationalEvent[] = [
  {
    id: "OE-seed-1",
    atIso: "2026-09-13T05:02:00.000Z",
    stage: "sense",
    type: "Signal ingested",
    shipmentId: "SF-2043",
    message: "Suez transit advisory ingested — below action threshold, monitoring continued.",
    status: "info",
    seeded: true,
  },
  {
    id: "OE-seed-2",
    atIso: "2026-09-13T05:31:00.000Z",
    stage: "sense",
    type: "Source verification",
    shipmentId: "SF-2044",
    message: "Reefer custody check passed at Valencia departure.",
    status: "success",
    seeded: true,
  },
  {
    id: "OE-seed-3",
    atIso: "2026-09-13T05:56:00.000Z",
    stage: "ledger",
    type: "Audit",
    shipmentId: "SF-2042",
    message: "Ledger reconciliation complete — 8 historical entries verified.",
    status: "info",
    seeded: true,
  },
];
