import type { Shipment } from "../types/domain.js";
const eta = (days: number) => new Date(Date.now() + days * 86400000).toISOString();
export const shipments: Shipment[] = [
  {
    id: "SF-1001",
    origin: { name: "Ningbo", code: "CNNGB", lat: 29.87, lon: 121.54 },
    destination: { name: "Rotterdam", code: "NLRTM", lat: 51.95, lon: 4.14 },
    position: { lat: 12.4, lon: 60.2 },
    cargo: "Consumer electronics",
    cargoValueUsd: 180000,
    mode: "ocean",
    vessel: "MV Hanjin Meridian",
    etaIso: eta(15),
    riskScore: 38,
    status: "monitoring",
    coldChain: false,
    constraints: ["Contractual delivery window: 5 days float"],
    demoScenario: true,
    currentState: "MONITORED",
  },
  {
    id: "SF-1002",
    origin: { name: "Antwerp", code: "BEANR", lat: 51.26, lon: 4.4 },
    destination: { name: "Mombasa", code: "KEMBA", lat: -4.04, lon: 39.66 },
    position: { lat: 31.2, lon: 18.9 },
    cargo: "Vaccines (2–8 °C)",
    cargoValueUsd: 620000,
    mode: "ocean",
    vessel: "MV Scheldt Carrier",
    etaIso: eta(11),
    riskScore: 61,
    status: "monitoring",
    coldChain: true,
    constraints: [
      "COLD CHAIN: continuous 2–8 °C reefer custody",
      "GDP-certified handling at every transhipment",
    ],
    demoScenario: true,
    currentState: "MONITORED",
  },
  {
    id: "SF-1003",
    origin: { name: "Shanghai", code: "CNSHA", lat: 31.23, lon: 121.47 },
    destination: { name: "Los Angeles", code: "USLAX", lat: 33.74, lon: -118.27 },
    position: { lat: 34.8, lon: 168.4 },
    cargo: "Bulk pharma ingredients (API)",
    cargoValueUsd: 1450000,
    mode: "ocean",
    vessel: "MV Pacific Ridge",
    etaIso: eta(13),
    riskScore: 57,
    status: "monitoring",
    coldChain: false,
    constraints: ["Regulated substance: customs pre-clearance required"],
    demoScenario: true,
    currentState: "MONITORED",
  },
];
