import type { Shipment } from "../types/domain.js";
const eta = (days: number) => new Date(Date.now() + days * 86400000).toISOString();
export const shipments: Shipment[] = [
  {
    id: "SF-1001",
    origin: { name: "Ningbo", code: "CNNGB", lat: 29.87, lon: 121.54 },
    destination: { name: "Rotterdam", code: "NLRTM", lat: 51.95, lon: 4.14 },
    position: { lat: 12.4, lon: 60.2 },
    cargo: "Consumer electronics",
    cargoValueUsd: 180000,
    mode: "ocean",
    vessel: "MV Hanjin Meridian",
    etaIso: eta(15),
    riskScore: 38,
    status: "monitoring",
    coldChain: false,
    constraints: ["Contractual delivery window: 5 days float"],
    demoScenario: true,
    currentState: "MONITORED",
  },
  {
    id: "SF-1002",
    origin: { name: "Antwerp", code: "BEANR", lat: 51.26, lon: 4.4 },
    destination: { name: "Mombasa", code: "KEMBA", lat: -4.04, lon: 39.66 },
    position: { lat: 31.2, lon: 18.9 },
    cargo: "Vaccines (2–8 °C)",
    cargoValueUsd: 620000,
    mode: "ocean",
    vessel: "MV Scheldt Carrier",
    etaIso: eta(11),
    riskScore: 61,
    status: "monitoring",
    coldChain: true,
    constraints: [
      "COLD CHAIN: continuous 2–8 °C reefer custody",
      "GDP-certified handling at every transhipment",
    ],
    demoScenario: true,
    currentState: "MONITORED",
  },
  {
    id: "SF-1003",
    origin: { name: "Shanghai", code: "CNSHA", lat: 31.23, lon: 121.47 },
    destination: { name: "Los Angeles", code: "USLAX", lat: 33.74, lon: -118.27 },
    position: { lat: 34.8, lon: 168.4 },
    cargo: "Bulk pharma ingredients (API)",
    cargoValueUsd: 1450000,
    mode: "ocean",
    vessel: "MV Pacific Ridge",
    etaIso: eta(13),
    riskScore: 57,
    status: "monitoring",
    coldChain: false,
    constraints: ["Regulated substance: customs pre-clearance required"],
    demoScenario: true,
    currentState: "MONITORED",
  },
  {
    id: "SF-2041",
    origin: { name: "Santos", code: "BRSSZ", lat: -23.95, lon: -46.33 },
    destination: { name: "Hamburg", code: "DEHAM", lat: 53.54, lon: 9.98 },
    position: { lat: 5.2, lon: -28.4 },
    cargo: "Green coffee",
    cargoValueUsd: 240000,
    mode: "ocean",
    vessel: "MV Atlantic Vale",
    etaIso: "2026-10-02T09:00:00.000Z",
    riskScore: 14,
    status: "on_track",
    coldChain: false,
    constraints: [],
    demoScenario: false,
    currentState: "MONITORED",
  },
  {
    id: "SF-2042",
    origin: { name: "Busan", code: "KRPUS", lat: 35.1, lon: 129.04 },
    destination: { name: "Seattle", code: "USSEA", lat: 47.6, lon: -122.34 },
    position: { lat: 44.1, lon: -172.6 },
    cargo: "Automotive components",
    cargoValueUsd: 410000,
    mode: "ocean",
    vessel: "MV Dongbaek",
    etaIso: "2026-09-22T12:00:00.000Z",
    riskScore: 22,
    status: "on_track",
    coldChain: false,
    constraints: [],
    demoScenario: false,
    currentState: "MONITORED",
  },
  {
    id: "SF-2043",
    origin: { name: "Jebel Ali", code: "AEJEA", lat: 25.01, lon: 55.06 },
    destination: { name: "Felixstowe", code: "GBFXT", lat: 51.95, lon: 1.32 },
    position: { lat: 26.7, lon: 33.1 },
    cargo: "Industrial polymers",
    cargoValueUsd: 305000,
    mode: "ocean",
    vessel: "MV Al Maha",
    etaIso: "2026-09-29T18:00:00.000Z",
    riskScore: 31,
    status: "monitoring",
    coldChain: false,
    constraints: ["Suez transit dependency"],
    demoScenario: false,
    currentState: "MONITORED",
  },
  {
    id: "SF-2044",
    origin: { name: "Valencia", code: "ESVLC", lat: 39.44, lon: -0.31 },
    destination: { name: "New York", code: "USNYC", lat: 40.67, lon: -74.05 },
    position: { lat: 38.2, lon: -37.9 },
    cargo: "Chilled dairy (0–4 °C)",
    cargoValueUsd: 185000,
    mode: "ocean",
    vessel: "MV Turia Reefer",
    etaIso: "2026-09-21T07:00:00.000Z",
    riskScore: 27,
    status: "on_track",
    coldChain: true,
    constraints: ["COLD CHAIN: continuous 0–4 °C custody"],
    demoScenario: false,
    currentState: "MONITORED",
  },
  {
    id: "SF-2045",
    origin: { name: "Chennai", code: "INMAA", lat: 13.09, lon: 80.29 },
    destination: { name: "Durban", code: "ZADUR", lat: -29.87, lon: 31.02 },
    position: { lat: -3.4, lon: 63.8 },
    cargo: "Textiles",
    cargoValueUsd: 96000,
    mode: "ocean",
    vessel: "MV Coromandel",
    etaIso: "2026-10-05T10:00:00.000Z",
    riskScore: 9,
    status: "on_track",
    coldChain: false,
    constraints: [],
    demoScenario: false,
    currentState: "MONITORED",
  },
];
