/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApproverRouteImport } from './routes/approver'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ApiDecideRouteImport } from './routes/api/decide'
import { Route as LedgerIndexRouteImport } from './routes/ledger.index'
import { Route as LedgerEntryIdRouteImport } from './routes/ledger.$entryId'
import { Route as ShipmentIdRouteImport } from './routes/shipment.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverRoute = ApproverRouteImport.update({
  id: '/approver',
  path: '/approver',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecideRoute = ApiDecideRouteImport.update({
  id: '/api/decide',
  path: '/api/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerEntryIdRoute = LedgerEntryIdRouteImport.update({
  id: '/ledger/$entryId',
  path: '/ledger/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentIdRoute = ShipmentIdRouteImport.update({
  id: '/shipment/$id',
  path: '/shipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approver': typeof ApproverRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/api/decide': typeof ApiDecideRoute
  '/ledger/$entryId': typeof LedgerEntryIdRoute
  '/shipment/$id': typeof ShipmentIdRoute
  '/ledger/': typeof LedgerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approver': typeof ApproverRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/api/decide': typeof ApiDecideRoute
  '/ledger/$entryId': typeof LedgerEntryIdRoute
  '/shipment/$id': typeof ShipmentIdRoute
  '/ledger': typeof LedgerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approver': typeof ApproverRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/api/decide': typeof ApiDecideRoute
  '/ledger/$entryId': typeof LedgerEntryIdRoute
  '/shipment/$id': typeof ShipmentIdRoute
  '/ledger/': typeof LedgerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approver'
    | '/login'
    | '/planner'
    | '/api/decide'
    | '/ledger/$entryId'
    | '/shipment/$id'
    | '/ledger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approver'
    | '/login'
    | '/planner'
    | '/api/decide'
    | '/ledger/$entryId'
    | '/shipment/$id'
    | '/ledger'
  id:
    | '__root__'
    | '/'
    | '/approver'
    | '/login'
    | '/planner'
    | '/api/decide'
    | '/ledger/$entryId'
    | '/shipment/$id'
    | '/ledger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproverRoute: typeof ApproverRoute
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  ApiDecideRoute: typeof ApiDecideRoute
  LedgerEntryIdRoute: typeof LedgerEntryIdRoute
  ShipmentIdRoute: typeof ShipmentIdRoute
  LedgerIndexRoute: typeof LedgerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver': {
      id: '/approver'
      path: '/approver'
      fullPath: '/approver'
      preLoaderRoute: typeof ApproverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decide': {
      id: '/api/decide'
      path: '/api/decide'
      fullPath: '/api/decide'
      preLoaderRoute: typeof ApiDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/': {
      id: '/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/$entryId': {
      id: '/ledger/$entryId'
      path: '/ledger/$entryId'
      fullPath: '/ledger/$entryId'
      preLoaderRoute: typeof LedgerEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipment/$id': {
      id: '/shipment/$id'
      path: '/shipment/$id'
      fullPath: '/shipment/$id'
      preLoaderRoute: typeof ShipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproverRoute: ApproverRoute,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  ApiDecideRoute: ApiDecideRoute,
  LedgerEntryIdRoute: LedgerEntryIdRoute,
  ShipmentIdRoute: ShipmentIdRoute,
  LedgerIndexRoute: LedgerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
