/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApproverRouteImport } from './routes/approver'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as LedgerIndexRouteImport } from './routes/ledger.index'
import { Route as LedgerEntryIdRouteImport } from './routes/ledger.$entryId'
import { Route as ShipmentIdRouteImport } from './routes/shipment.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproverRoute = ApproverRouteImport.update({
  id: '/approver',
  path: '/approver',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerEntryIdRoute = LedgerEntryIdRouteImport.update({
  id: '/ledger/$entryId',
  path: '/ledger/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentIdRoute = ShipmentIdRouteImport.update({
  id: '/shipment/$id',
  path: '/shipment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approver': typeof ApproverRoute
  '/case-studies': typeof CaseStudiesRoute
  '/editor': typeof EditorRoute
  '/integrity': typeof IntegrityRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/scenarios': typeof ScenariosRoute
  '/shipments': typeof ShipmentsRoute
  '/ledger/$entryId': typeof LedgerEntryIdRoute
  '/shipment/$id': typeof ShipmentIdRoute
  '/ledger/': typeof LedgerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approver': typeof ApproverRoute
  '/case-studies': typeof CaseStudiesRoute
  '/editor': typeof EditorRoute
  '/integrity': typeof IntegrityRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/scenarios': typeof ScenariosRoute
  '/shipments': typeof ShipmentsRoute
  '/ledger/$entryId': typeof LedgerEntryIdRoute
  '/shipment/$id': typeof ShipmentIdRoute
  '/ledger': typeof LedgerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approver': typeof ApproverRoute
  '/case-studies': typeof CaseStudiesRoute
  '/editor': typeof EditorRoute
  '/integrity': typeof IntegrityRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/scenarios': typeof ScenariosRoute
  '/shipments': typeof ShipmentsRoute
  '/ledger/$entryId': typeof LedgerEntryIdRoute
  '/shipment/$id': typeof ShipmentIdRoute
  '/ledger/': typeof LedgerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approver'
    | '/case-studies'
    | '/editor'
    | '/integrity'
    | '/login'
    | '/planner'
    | '/scenarios'
    | '/shipments'
    | '/ledger/$entryId'
    | '/shipment/$id'
    | '/ledger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approver'
    | '/case-studies'
    | '/editor'
    | '/integrity'
    | '/login'
    | '/planner'
    | '/scenarios'
    | '/shipments'
    | '/ledger/$entryId'
    | '/shipment/$id'
    | '/ledger'
  id:
    | '__root__'
    | '/'
    | '/approver'
    | '/case-studies'
    | '/editor'
    | '/integrity'
    | '/login'
    | '/planner'
    | '/scenarios'
    | '/shipments'
    | '/ledger/$entryId'
    | '/shipment/$id'
    | '/ledger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApproverRoute: typeof ApproverRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  EditorRoute: typeof EditorRoute
  IntegrityRoute: typeof IntegrityRoute
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  ScenariosRoute: typeof ScenariosRoute
  ShipmentsRoute: typeof ShipmentsRoute
  LedgerEntryIdRoute: typeof LedgerEntryIdRoute
  ShipmentIdRoute: typeof ShipmentIdRoute
  LedgerIndexRoute: typeof LedgerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approver': {
      id: '/approver'
      path: '/approver'
      fullPath: '/approver'
      preLoaderRoute: typeof ApproverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/': {
      id: '/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/$entryId': {
      id: '/ledger/$entryId'
      path: '/ledger/$entryId'
      fullPath: '/ledger/$entryId'
      preLoaderRoute: typeof LedgerEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipment/$id': {
      id: '/shipment/$id'
      path: '/shipment/$id'
      fullPath: '/shipment/$id'
      preLoaderRoute: typeof ShipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApproverRoute: ApproverRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  EditorRoute: EditorRoute,
  IntegrityRoute: IntegrityRoute,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  ScenariosRoute: ScenariosRoute,
  ShipmentsRoute: ShipmentsRoute,
  LedgerEntryIdRoute: LedgerEntryIdRoute,
  ShipmentIdRoute: ShipmentIdRoute,
  LedgerIndexRoute: LedgerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
